service: duomo-app
frameworkVersion: '3'

package:
  artifact: build/libs/duomo-1.0.0-aws.jar

provider:
  name: aws
  runtime: java11
  profile: serverless-admin
  region: eu-central-1
  timeout: 10
  memorySize: 1024
  logRetentionInDays: 7
#  iam:
#    role:
#      statements:
#        - Effect: 'Allow'
#          Action:
#            - 's3:*'
#          Resource:
#            - 'arn:aws:s3:::${self:custom.thumbnailBucket}/*'
#            - !Join ['', ['arn:aws:s3:::', !Ref ServerlessDeploymentBucket, '/*']]

functions:
  duomo-app-api:
    handler: xyz.wirklich.duomo.StreamLambdaHandler
    events:
      - http:
          path: /times
          method: post
    timeout: 30
